[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mip_collections = "C6vmifH7NSUttWfCREMUF5jGjFAn74aXT6pcSCowvpGq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
